import type { Metadata } from "next";
import { breadcrumbSchema, businessSchema, defaultImage, graphSchema, siteUrl } from "../seo";

export const metadata: Metadata = {
  title: "Team | Immobilienmakler Bergisch Gladbach",
  description: "Das Team von Stark & Hoffmann Immobilien in Bergisch Gladbach: persönliche Ansprechpartner für Immobilienbewertung, Verkauf und Vermietung.",
  alternates: { canonical: `${siteUrl}/team/` },
  openGraph: { title: "Unser Team | Stark & Hoffmann Immobilien", description: "Ihre persönlichen Ansprechpartner in Bergisch Gladbach.", url: `${siteUrl}/team/`, images: [defaultImage] },
  twitter: { card: "summary_large_image", images: [defaultImage] },
};

const team = [
  { name: "Patrick Stark", role: "Lizenzpartner", image: "patrick.jpg", bio: "Verbindet sein starkes Netzwerk in Bergisch Gladbach mit Fachwissen zu Baustruktur und Architektur. Er begleitet Eigentümer transparent, ehrlich und mit Gespür für die persönliche Bedeutung eines Verkaufs.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/patrick-stark/" },
  { name: "Julian Hoffmann", role: "Lizenzpartner", image: "julian.jpg", bio: "Bringt betriebswirtschaftliche und internationale Vertriebserfahrung ein. Sein Anspruch: ein professioneller, transparenter Verkaufsprozess, geprägt von Vertrauen, Kommunikation und Verlässlichkeit.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/julian-hoffmann/" },
  { name: "Johannes Brauns", role: "Teamlead Acquisition", image: "jo.jpg", bio: "Ist seit mehr als 20 Jahren in der Immobilienbranche tätig. Als erster Ansprechpartner berät er Eigentümer persönlich, erkennt Potenziale und bereitet den Verkauf strukturiert und transparent vor.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/johannes-brauns/" },
  { name: "Vanessa Rogge", role: "Assistenz der Geschäftsführung", image: "vanessa.jpg", bio: "Unterstützt die Geschäftsführung und begleitet die organisatorischen Abläufe im Team Bergisch Gladbach.", profile: null },
  { name: "Doreen Kaschner", role: "Operations & Marketing Managerin", image: "doreen.jpg", bio: "Koordiniert operative Prozesse und das Marketing des Teams in Bergisch Gladbach.", profile: null },
  { name: "Joelle Hoffmann", role: "Social Media Creator", image: "joelle.jpg", bio: "Verantwortet die Inhalte und die Darstellung des Teams in den sozialen Medien.", profile: null },
  { name: "Bernd Breuer", role: "Selbstständiger Senior Immobilienmakler", image: "bernd.jpg", bio: "Kennt Refrath und die Region aus langjähriger eigener Erfahrung. Er verbindet lokale Marktkenntnis, Vertriebserfahrung und die Perspektive von Eigentümern und Investoren.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/bernd-breuer/" },
  { name: "Christian Engelke", role: "Selbstständiger Immobilienmakler", image: "christian.jpg", bio: "Berät in Bergisch Gladbach und Leverkusen. Eigene Erfahrungen mit Kauf, Vermietung und Verwaltung von Immobilien bilden die praktische Grundlage seiner Beratung.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/christian-engelke/" },
  { name: "Luba Schneider", role: "Selbstständige Senior Immobilienmaklerin", image: "luba.jpg", bio: "Bringt mehr als 15 Jahre Erfahrung aus Wohnungswirtschaft und Marketing mit. Sie steht für persönliche, engagierte Begleitung und ein offenes Ohr in jeder Verkaufsphase.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/luba-schneider/" },
  { name: "Mario Mentel", role: "Selbstständiger Immobilienmakler", image: "mario.jpg", bio: "Verbindet langjährige Projekt- und Organisationserfahrung aus der Medienbranche mit eigener Praxis in Entwicklung und Vermietung von Immobilien.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/mario-mentel/" },
  { name: "Robin Köppe", role: "Selbstständiger Immobilienmakler", image: "robin.jpg", bio: "Ist tief in Leverkusen und dem Bergischen Land verwurzelt. Nach 25 Jahren in verantwortlichen Vertriebspositionen setzt er auf ehrliche Beratung, Verlässlichkeit und persönlichen Einsatz.", profile: "https://www.evernest.com/de/unsere-makler/leverkusen/robin-koeppe/" },
  { name: "Sarah Di Gangi", role: "Selbstständige Immobilienmaklerin", image: "sarah.jpg", bio: "Verfügt über mehr als 15 Jahre Branchenerfahrung aus Immobilienvertrieb und Projektentwicklung. Qualität, Architektur und die individuellen Bedürfnisse ihrer Kunden stehen im Mittelpunkt.", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/sarah-di-gangi/" },
] as const;

export default function TeamPage() {
  const url = `${siteUrl}/team/`;
  const schema = graphSchema(businessSchema, breadcrumbSchema([{ name: "Startseite", url: siteUrl }, { name: "Team", url }]), ...team.map(({ name, role, image, profile }) => ({ "@type": "Person", name, jobTitle: role, image: `${siteUrl}/team/${image}`, worksFor: { "@id": `${siteUrl}/#immobilienmakler` }, ...(profile ? { sameAs: profile } : {}) })));
  return <main className="team-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="site-header"><a className="brand" href="/"><span className="brand-mark">S<span>&amp;</span>H</span><span><strong>Stark &amp; Hoffmann</strong><small>Immobilien · Bergisch Gladbach</small></span></a><nav aria-label="Seitennavigation"><a href="/#profil">Profil</a><a href="/team/">Team</a><a href="/#markt">Markt</a><a href="/#staedte">Region</a></nav><a className="header-cta" href="/immobilienbewertung/">Kostenlose Bewertung</a></header>
    <section className="team-hero"><div><p className="eyebrow light">Stark &amp; Hoffmann Immobilien</p><h1>Unser Team in Bergisch Gladbach.</h1><p>Persönliche Ansprechpartner, lokale Marktkenntnis und ein gemeinsames Ziel: Eigentümer vom ersten Gespräch bis zum erfolgreichen Abschluss verlässlich zu begleiten.</p></div></section>
    <section className="team-content section"><div className="section-head"><div><p className="eyebrow">Menschen vor Ort</p><h2>Das Team hinter Stark &amp; Hoffmann.</h2></div><p>Wir verbinden persönliche Beratung mit professioneller Bewertung, Vermarktung und Verkaufsbegleitung in Bergisch Gladbach und der Region.</p></div><div className="team-grid">{team.map(({ name, role, image, bio, profile }) => <article className="team-card" key={name}><img src={`/team/${image}`} alt={`${name} – ${role} bei Stark & Hoffmann Immobilien Bergisch Gladbach`} loading="lazy"/><div><h3>{name}</h3><p className="team-role">{role}</p><p className="team-bio">{bio}</p>{profile && <a className="team-profile-link" href={profile} target="_blank" rel="noreferrer">Profil und Quelle bei Evernest ↗</a>}</div></article>)}</div></section>
    <section className="district-contact section"><div><p className="eyebrow light">Persönlich kennenlernen</p><h2>Sprechen wir über Ihre Immobilie.</h2><p>Unser Team begleitet Sie bei Bewertung, Verkauf und Vermietung in Bergisch Gladbach.</p></div><div><a className="button gold" href="/immobilienbewertung/">Bewertung starten</a><a href="tel:+4922049147881">+49 2204 914 7881</a></div></section>
    <footer><div className="footer-brand"><span className="brand-mark">S<span>&amp;</span>H</span><div><strong>Stark &amp; Hoffmann Immobilien</strong><small>Evernest Lizenzpartner Bergisch Gladbach</small></div></div><div><h4>Kontakt</h4><p>Schloßstraße 41<br/>51429 Bergisch Gladbach</p><a href="tel:+4922049147881">+49 2204 914 7881</a><a href="https://www.instagram.com/evernest.bergischgladbach/" target="_blank" rel="noreferrer">Instagram ↗</a></div><div><h4>Unternehmen</h4><a href="/">Startseite</a><a href="/team/">Team</a><a href="/downloads/">Downloads</a></div><div><h4>Rechtliches</h4><a href="/impressum/">Impressum</a><a href="/agb/">AGB</a><a href="/datenschutz/">Datenschutz</a></div></footer>
  </main>;
}
