import googleReviews from "@/app/google-reviews.json";
// Footer nach Evernest-Vorbild (28.09.2026): Anschrift, Unternehmen, Bewertung, Immobilien & Ratgeber.
const googleUrl="https://www.google.com/maps/place/Evernest+Bergisch+Gladbach+-+Stark+%26+Hoffmann+Immobilien+GmbH/";
export default function SiteFooter(){
  return <footer className="site-footer">
    <div className="sf-grid">
      <div className="sf-col"><p className="sf-h">Anschrift</p><address>Stark & Hoffmann Immobilien GmbH<br/>Evernest Lizenzpartner Bergisch Gladbach<br/>Schloßstraße 41<br/>51429 Bergisch Gladbach</address><p><a href="mailto:bergischgladbach@evernest.com">bergischgladbach@evernest.com</a><br/><a href="tel:+4922049147881">+49 2204 914 7881</a></p><a className="sf-google" href={googleUrl} target="_blank" rel="noreferrer"><strong>{googleReviews.rating}</strong><span className="sf-stars">★★★★★</span><span>{googleReviews.count} Rezensionen auf Google</span></a></div>
      <div className="sf-col"><p className="sf-h">Unternehmen</p><ul className="sf-list"><li><a href="/#profil">Über uns</a></li><li><a href="/team/">Team</a></li><li><a href="/downloads/">Downloads</a></li><li><a href="https://www.evernest.com/de/unsere-makler/bergisch-gladbach/" target="_blank" rel="noreferrer">Evernest Bergisch Gladbach ↗</a></li><li><a href="/impressum/">Impressum</a></li><li><a href="/datenschutz/">Datenschutz</a></li><li><a href="/agb/">AGB</a></li></ul></div>
      <div className="sf-col"><p className="sf-h">Kostenlose Bewertung</p><p>Was ist Ihre Immobilie wert? Online bewerten – kostenlos und unverbindlich.</p><a className="sf-btn" href="/immobilienbewertung/">Online-Immobilienbewertung</a><p className="sf-h">Folgen</p><div className="sf-social"><a href="https://www.instagram.com/evernest.bergischgladbach/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a></div></div>
      <div className="sf-col"><p className="sf-h">Immobilien &amp; Ratgeber</p><ul className="sf-list"><li><a href="/haus-verkaufen-bergisch-gladbach/">Haus verkaufen</a></li><li><a href="/wohnung-verkaufen-bergisch-gladbach/">Wohnung verkaufen</a></li><li><a href="/grundstueck-verkaufen-bergisch-gladbach/">Grundstück verkaufen</a></li><li><a href="/immobilienbewertung/">Immobilie bewerten</a></li><li><a href="/#immobilien">Immobilienangebote</a></li><li><a href="/#staedte">Ihr Stadtteil</a></li><li><a href="/bergisch-gladbach/">Immobilienpreise Bergisch Gladbach</a></li><li><a href="/ratgeber/">Ratgeber</a></li></ul></div>
    </div>
    <div className="sf-bottom"><span>© 2026 Stark &amp; Hoffmann Immobilien GmbH · Amtsgericht Köln, HRB 116396 · Geschäftsführer: Patrick Stark, Julian Hoffmann</span><span>Alle Angaben unverbindlich. Irrtümer und Änderungen vorbehalten.</span></div>
  </footer>;
}
