export type District = { slug:string; name:string; code:string; inhabitants:string; area:string; profile:string; wiki:string; brw?:string; brwGroup?:string };

export const districts: District[] = [
  {slug:"schildgen",name:"Schildgen",code:"11",inhabitants:"6.151",area:"Statistischer Bezirk 1",profile:"Schildgen liegt im Nordwesten Bergisch Gladbachs zwischen Katterbach und Nußbaum und grenzt zudem an Köln, Leverkusen und Odenthal. Weite Teile gehörten bis zur kommunalen Neugliederung 1975 zur Gemeinde Odenthal; Nittum gilt als ältester Siedlungskern des heutigen Stadtteils.",wiki:"https://de.wikipedia.org/wiki/Schildgen",brw:"490–660",brwGroup:"Schildgen"},
  {slug:"katterbach",name:"Katterbach",code:"12",inhabitants:"4.990",area:"Statistischer Bezirk 1",profile:"Katterbach liegt im Nordwesten der Stadt und grenzt an Schildgen, Nußbaum, Paffrath und Köln. Wikipedia beschreibt die Siedlung als vermutlich fränkische Gründung und damit als einen der ältesten frühmittelalterlichen Siedlungskerne im heutigen Stadtgebiet.",wiki:"https://de.wikipedia.org/wiki/Katterbach_(Bergisch_Gladbach)"},
  {slug:"nussbaum",name:"Nußbaum",code:"13",inhabitants:"1.092",area:"Statistischer Bezirk 1",profile:"Nußbaum liegt im Norden Bergisch Gladbachs zwischen Katterbach, Schildgen, Hebborn und Paffrath und grenzt an Odenthal. Der Ort entstand aus einer spätmittelalterlichen Hofgründung; 1448 ist der Name als „Nusboem“ belegt.",wiki:"https://de.wikipedia.org/wiki/Nu%C3%9Fbaum_(Bergisch_Gladbach)",brw:"540–720",brwGroup:"Paffrath / Nußbaum"},
  {slug:"paffrath",name:"Paffrath",code:"14",inhabitants:"7.076",area:"Statistischer Bezirk 1",profile:"Paffrath liegt im Nordwesten Bergisch Gladbachs, rund 15 Kilometer östlich von Köln. Der Ort ging aus einer frühmittelalterlichen Siedlung des Kölner Domkapitels hervor, wurde 1160 erstmals urkundlich erwähnt und wird von der romanischen Kirche St. Clemens geprägt.",wiki:"https://de.wikipedia.org/wiki/Paffrath",brw:"540–720",brwGroup:"Paffrath / Nußbaum"},
  {slug:"hand",name:"Hand",code:"15",inhabitants:"8.865",area:"Statistischer Bezirk 1",profile:"Hand liegt im Westen der Stadt und grenzt an Paffrath, Gronau und Köln. Der Stadtteil entwickelte sich aus einer frühneuzeitlichen Siedlungsgründung, die 1594 erstmals als „Gut an der Handt“ erwähnt wurde.",wiki:"https://de.wikipedia.org/wiki/Hand_(Bergisch_Gladbach)",brw:"510–660",brwGroup:"Hand"},
  {slug:"stadtmitte",name:"Stadtmitte",code:"21",inhabitants:"11.875",area:"Statistischer Bezirk 2",profile:"Die Stadtmitte ist der zentrale Stadtteil Bergisch Gladbachs und grenzt an sieben weitere Stadtteile. Der heutige Name wurde 1999 festgelegt; zuvor trug der Wohnplatz die Bezeichnung Gladbach, die wiederholt zu Missverständnissen mit dem gesamten Stadtgebiet geführt hatte.",wiki:"https://de.wikipedia.org/wiki/Stadtmitte_(Bergisch_Gladbach)",brw:"480–720",brwGroup:"Gladbach"},
  {slug:"hebborn",name:"Hebborn",code:"22",inhabitants:"5.943",area:"Statistischer Bezirk 2",profile:"Hebborn grenzt an Nußbaum, Romaney, Stadtmitte und Paffrath sowie im Norden an Odenthal. Der Hebborner Hof war eine hochmittelalterliche Siedlungsgründung der Grafen von Berg und ist 1280 erstmals als „Hadeburne“ belegt.",wiki:"https://de.wikipedia.org/wiki/Hebborn"},
  {slug:"heidkamp",name:"Heidkamp",code:"23",inhabitants:"6.551",area:"Statistischer Bezirk 2",profile:"Heidkamp liegt zwischen Gronau, Stadtmitte, Sand und Lückerath. Die Siedlung entwickelte sich aus einer 1582 erstmals belegten Hofgründung; mit der Industrialisierung entstanden Unter-, Mittel- und Oberheidkamp.",wiki:"https://de.wikipedia.org/wiki/Heidkamp_(Bergisch_Gladbach)"},
  {slug:"gronau",name:"Gronau",code:"24",inhabitants:"6.407",area:"Statistischer Bezirk 2",profile:"Gronau liegt im Westen der Stadt, wird von der Strunde durchzogen und grenzt unter anderem an Köln. Der Name wird auf „Groenauwe“ im Sinne einer grünen Aue zurückgeführt; die früher landwirtschaftlich geprägte Auenlandschaft wandelte sich zu einem Wohn- und Industriestandort.",wiki:"https://de.wikipedia.org/wiki/Gronau_(Bergisch_Gladbach)"},
  {slug:"romaney",name:"Romaney",code:"31",inhabitants:"722",area:"Statistischer Bezirk 3",profile:"Romaney grenzt an Hebborn, Herrenstrunden und Stadtmitte sowie im Norden an Odenthal. Der Weiler entstand vermutlich im Spätmittelalter und wurde 1448 erstmals unter der Bezeichnung „Rumenye“ erwähnt.",wiki:"https://de.wikipedia.org/wiki/Romaney"},
  {slug:"herrenstrunden",name:"Herrenstrunden",code:"32",inhabitants:"911",area:"Statistischer Bezirk 3",profile:"Herrenstrunden liegt im äußersten Nordosten Bergisch Gladbachs am Beginn des Strundetals. Das Ortsbild wird von der ehemaligen Johanniterkomturei und der alten Johanniterkirche geprägt; die Komturei an der Strunde ist erstmals für das Jahr 1300 belegt.",wiki:"https://de.wikipedia.org/wiki/Herrenstrunden",brw:"400–490",brwGroup:"Herrenstrunden"},
  {slug:"sand",name:"Sand",code:"33",inhabitants:"2.510",area:"Statistischer Bezirk 3",profile:"Sand liegt in der Mitte Bergisch Gladbachs und grenzt an sieben Stadtteile. Das Kirchdorf zählt zu den frühen Siedlungskernen im Stadtgebiet; eine Urkunde des Klosters Meer nennt Sand 1229, die Form „van me Sande“ ist für 1349 belegt.",wiki:"https://de.wikipedia.org/wiki/Sand_(Bergisch_Gladbach)"},
  {slug:"herkenrath",name:"Herkenrath",code:"41",inhabitants:"3.631",area:"Statistischer Bezirk 4",profile:"Herkenrath grenzt an Sand, Herrenstrunden, Asselborn, Bärbroich und Moitzfeld. Der Ort wird 1163/1164 im Codex Thioderici als Pfarrei genannt; um 1224 wurde die Kirche dem Johanniterorden übertragen.",wiki:"https://de.wikipedia.org/wiki/Herkenrath",brw:"430–540",brwGroup:"Herkenrath"},
  {slug:"asselborn",name:"Asselborn",code:"42",inhabitants:"882",area:"Statistischer Bezirk 4",profile:"Asselborn liegt im nordöstlichen Teil Bergisch Gladbachs nahe der Grenze zu Kürten. Der mittelalterliche Siedlungsname ist 1294 als „de Astelburne“ nachgewiesen und bezeichnet zugleich ein ehemaliges Rittergut.",wiki:"https://de.wikipedia.org/wiki/Asselborn_(Bergisch_Gladbach)"},
  {slug:"baerbroich",name:"Bärbroich",code:"43",inhabitants:"1.280",area:"Statistischer Bezirk 4",profile:"Bärbroich grenzt an Asselborn, Moitzfeld und Herkenrath sowie an Kürten. Der Ort entstand vermutlich erst in der zweiten Hälfte des 19. Jahrhunderts aus mehreren Weilern; in seiner Umgebung waren damals verschiedene Bergwerke in Betrieb.",wiki:"https://de.wikipedia.org/wiki/B%C3%A4rbroich"},
  {slug:"lueckerath",name:"Lückerath",code:"51",inhabitants:"4.177",area:"Statistischer Bezirk 5",profile:"Lückerath liegt zwischen Kippekausen, Gronau, Heidkamp, Sand, Bensberg, Kaule und Frankenforst. Die Siedlung entstand in der großen Rodungsperiode zwischen 1000 und 1300; Lückerath und Oberlückerath bestehen weiterhin als Ortsteile innerhalb des Stadtteils.",wiki:"https://de.wikipedia.org/wiki/L%C3%BCckerath"},
  {slug:"bensberg",name:"Bensberg",code:"52",inhabitants:"5.757",area:"Statistischer Bezirk 5",profile:"Bensberg wurde 1139 erstmals urkundlich erwähnt und war von 1947 bis zur kommunalen Neugliederung 1975 eine eigenständige Stadt. Der Stadtteil grenzt an Sand, Moitzfeld, Bockenberg, Kaule und Lückerath.",wiki:"https://de.wikipedia.org/wiki/Bensberg",brw:"570–930",brwGroup:"Bensberg"},
  {slug:"bockenberg",name:"Bockenberg",code:"53",inhabitants:"3.083",area:"Statistischer Bezirk 5",profile:"Bockenberg liegt im Süden der Stadt am Westabfall des Bergischen Landes zur Kölner Bucht; große Teile des Stadtteilgebiets liegen südlich der A4 im Königsforst. 1887 entstand hier der „Luftkurort Bockenberg“, der auch Kölner Ausflugsgäste anzog.",wiki:"https://de.wikipedia.org/wiki/Bockenberg"},
  {slug:"kaule",name:"Kaule",code:"54",inhabitants:"3.997",area:"Statistischer Bezirk 5",profile:"Kaule liegt im Süden Bergisch Gladbachs zwischen Frankenforst, Lückerath, Bensberg und Bockenberg. Der Name geht auf mittelalterliche Hofstellen „auf der Kaule“ zurück und wird vom mittelhochdeutschen „kûle“ für eine Grube oder künstliche Vertiefung hergeleitet.",wiki:"https://de.wikipedia.org/wiki/Kaule_(Bergisch_Gladbach)"},
  {slug:"moitzfeld",name:"Moitzfeld",code:"55",inhabitants:"4.491",area:"Statistischer Bezirk 5",profile:"Moitzfeld liegt im Südosten Bergisch Gladbachs und grenzt im Süden und Südosten an Overath. Der heutige Ort entwickelte sich aus drei Siedlungskernen; die Siedlungsgründung wird auf das Hochmittelalter datiert und ist 1550 als „Moisfeld“ belegt.",wiki:"https://de.wikipedia.org/wiki/Moitzfeld",brw:"480–630",brwGroup:"Moitzfeld"},
  {slug:"refrath",name:"Refrath",code:"61",inhabitants:"9.437",area:"Statistischer Bezirk 6",profile:"Refrath liegt im Westen Bergisch Gladbachs an der Grenze zu Köln. Der Ortsname wird als Verbindung von „Ref“ für Ufer und „rath“ für Rodung erklärt; sichere schriftliche Nachweise zur Ortsgeschichte reichen in das 12. Jahrhundert zurück.",wiki:"https://de.wikipedia.org/wiki/Refrath",brw:"790–970",brwGroup:"Refrath"},
  {slug:"alt-refrath",name:"Alt-Refrath",code:"62",inhabitants:"3.261",area:"Statistischer Bezirk 6",profile:"Alt-Refrath grenzt an Refrath, Gronau und Kippekausen. Der Stadtteil gilt als ältester Siedlungskern des Refrather Raums; erste Rodungen werden dort bereits für das 9. Jahrhundert angenommen.",wiki:"https://de.wikipedia.org/wiki/Alt-Refrath"},
  {slug:"kippekausen",name:"Kippekausen",code:"63",inhabitants:"2.530",area:"Statistischer Bezirk 6",profile:"Kippekausen liegt zwischen Refrath, Alt-Refrath, Gronau, Lückerath und Frankenforst. Der Name bezieht sich auf die hochmittelalterliche Motte Kippekausen, eine um das Jahr 1000 errichtete Burganlage.",wiki:"https://de.wikipedia.org/wiki/Kippekausen"},
  {slug:"frankenforst",name:"Frankenforst",code:"64",inhabitants:"5.452",area:"Statistischer Bezirk 6",profile:"Frankenforst liegt im Süden Bergisch Gladbachs; ein großer Teil des Stadtteilgebiets südlich der A4 gehört zum unbewohnten Königsforst. Um 1900 entstand in Alt-Frankenforst eine Parksiedlung mit Villen, während sich Neu-Frankenforst seit den 1920er-Jahren entwickelte.",wiki:"https://de.wikipedia.org/wiki/Frankenforst"},
  {slug:"lustheide",name:"Lustheide",code:"65",inhabitants:"3.401",area:"Statistischer Bezirk 6",profile:"Lustheide liegt im Südwesten Bergisch Gladbachs an der Stadtgrenze zu Köln und wird unter anderem von der A4 und der Stadtbahnlinie 1 begrenzt. Der Name geht auf eine hochmittelalterliche Hofstelle zurück; noch zu Beginn des 20. Jahrhunderts prägten Felder und einzelne Höfe das Gebiet.",wiki:"https://de.wikipedia.org/wiki/Lustheide"},
];

export const districtBySlug = (slug:string) => districts.find((item)=>item.slug===slug);
