"use client";

import { useEffect, useState } from "react";
import StreetSearch, { type ResolvedAddress } from "./StreetSearch";

const propertyTypes=[["Wohnung","▤","Eigentumswohnung oder Teileigentum"],["Haus","⌂","Ein- oder Zweifamilienhaus"],["Mehrfamilienhaus","▥","Mehrere Wohneinheiten"],["Grundstück","◇","Unbebautes Grundstück"]];
const conditions=[["1 – Sehr gut","Neuwertig oder umfassend saniert"],["2 – Gut","Modernisiert und gut ausgestattet"],["3 – Befriedigend","Gepflegt und altersgemäß"],["4 – Ausreichend","Leichter Renovierungsbedarf"],["5 – Mangelhaft","Deutlicher Modernisierungsbedarf"],["6 – Ungenügend","Sanierungsstau und hoher Aufwand"]];
type ValuationData = Record<string,string>;

export default function BewertungsForm(){
  const [step,setStep]=useState(1); const [sent,setSent]=useState(false); const [addressValid,setAddressValid]=useState(false);
  const [data,setData]=useState<ValuationData>({type:"",street:"",number:"",zip:"",district:"",city:"Bergisch Gladbach",living:"",plot:"",rooms:"",units:"",development:"",rentCurrentMonth:"",rentCurrentYear:"",rentTargetMonth:"",rentTargetYear:"",condition:"",year:"",first:"",last:"",email:"",phone:"",contactAddress:"",contactZip:"",contactCity:"",consent:""});
  const update=(key:string,value:string)=>setData(prev=>prev[key]===value?prev:{...prev,[key]:value});
  useEffect(()=>{const street=new URLSearchParams(window.location.search).get("street");if(street)update("street",street);},[]);
  const resolved=(result:ResolvedAddress)=>{setAddressValid(result.valid);update("zip",result.zip);update("district",result.district);};
  const next=()=>setStep(value=>Math.min(7,value+1)); const back=()=>setStep(value=>Math.max(1,value-1));
  const hasSize=data.type==="Grundstück"?!!data.plot:!!data.living;
  const canContinue=step===1?!!data.type:step===2?!!data.street&&addressValid:step===3?hasSize:step===5?!!data.condition&&!!data.year:step===6?!!data.first&&!!data.last&&!!data.email&&!!data.phone&&data.consent==="yes":true;
  const submit=()=>{const subject=`Immobilienbewertung ${data.street} ${data.number}, Bergisch Gladbach`;const body=[`Immobilientyp: ${data.type}`,`Adresse: ${data.street} ${data.number}, ${data.zip} Bergisch Gladbach-${data.district}`,`Wohnfläche: ${data.living||"–"} m²`,`Grundstück: ${data.plot||"–"} m²`,`Zimmer: ${data.rooms||"–"}`,`Wohneinheiten: ${data.units||"–"}`,`Erschließung: ${data.development||"–"}`,`Kaltmiete IST: ${data.rentCurrentMonth||"–"} monatlich / ${data.rentCurrentYear||"–"} jährlich`,`Kaltmiete SOLL: ${data.rentTargetMonth||"–"} monatlich / ${data.rentTargetYear||"–"} jährlich`,`Zustand: ${data.condition}`,`Baujahr: ${data.year}`,`Kontakt: ${data.first} ${data.last}, ${data.email}, ${data.phone}`,`Kontaktadresse: ${data.contactAddress||"–"}, ${data.contactZip||""} ${data.contactCity||""}`].join("\n");setSent(true);setStep(7);window.location.href=`mailto:bergischgladbach@evernest.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;};

  return <div className="valuation-tool"><div className="progress" aria-label={`Schritt ${step} von 7`}>{[1,2,3,4,5,6,7].map(n=><span className={n<=step?"active":""} key={n}>{n}</span>)}</div><div className="tool-panel">
    {step===1&&<><p className="eyebrow">Schritt 1 von 7</p><h2>Was möchten Sie bewerten?</h2><p className="tool-intro">Wählen Sie die Art Ihrer Immobilie.</p><div className="type-grid">{propertyTypes.map(([type,icon,description])=><button type="button" className={data.type===type?"selected":""} onClick={()=>update("type",type)} key={type}><span>{icon}</span><strong>{type}</strong><small>{description}</small></button>)}</div></>}
    {step===2&&<><p className="eyebrow">Schritt 2 von 7</p><h2>Wo liegt die Immobilie?</h2><p className="tool-intro">Suchen Sie die Straße. PLZ und Stadtteil werden aus dem Straßen-Master der Stadt Bergisch Gladbach zugeordnet.</p><StreetSearch street={data.street} houseNumber={data.number} onStreetChange={(value)=>update("street",value)} onHouseNumberChange={(value)=>update("number",value)} onResolve={resolved}/>{addressValid&&<div className="resolved-grid"><span>PLZ<strong>{data.zip}</strong></span><span>Ort<strong>Bergisch Gladbach</strong></span><span>Stadtteil<strong>{data.district}</strong></span></div>}<a className="data-source" href="https://www.bergischgladbach.de/strassenabfrage.aspx" target="_blank" rel="noreferrer">Quelle: Straßenabfrage der Stadt Bergisch Gladbach · Stand 22.08.2026 ↗</a></>}
    {step===3&&<><p className="eyebrow">Schritt 3 von 7</p><h2>Wie groß ist die Immobilie?</h2><p className="tool-intro">Geben Sie die vorhandenen Flächen an.</p>{data.type!=="Grundstück"&&<label>Wohnfläche in m² *<input type="number" min="1" value={data.living} onChange={e=>update("living",e.target.value)} placeholder="z. B. 120"/></label>}<label>Grundstücksfläche in m² {data.type==="Grundstück"&&"*"}<input type="number" min="1" value={data.plot} onChange={e=>update("plot",e.target.value)} placeholder="z. B. 450"/></label></>}
    {step===4&&<><p className="eyebrow">Schritt 4 von 7</p><h2>Weitere Angaben</h2><p className="tool-intro">Diese Angaben ermöglichen eine genauere persönliche Einordnung.</p><div className="form-row"><label>Anzahl Zimmer<input type="number" min="0" step="0.5" value={data.rooms} onChange={e=>update("rooms",e.target.value)} placeholder="z. B. 4"/></label><label>Wohneinheiten<input type="number" min="1" value={data.units} onChange={e=>update("units",e.target.value)} placeholder="z. B. 2"/></label></div>{data.type==="Grundstück"&&<label>Erschließungsstatus<select value={data.development} onChange={e=>update("development",e.target.value)}><option value="">Bitte auswählen</option><option>Erschlossen</option><option>Teilerschlossen</option><option>Nicht erschlossen</option><option>Unbekannt</option></select></label>}<div className="rent-grid"><label>Kaltmiete IST monatlich<input value={data.rentCurrentMonth} onChange={e=>update("rentCurrentMonth",e.target.value)} placeholder="z. B. 1.200 €"/></label><label>Kaltmiete IST jährlich<input value={data.rentCurrentYear} onChange={e=>update("rentCurrentYear",e.target.value)} placeholder="z. B. 14.400 €"/></label><label>Kaltmiete SOLL monatlich<input value={data.rentTargetMonth} onChange={e=>update("rentTargetMonth",e.target.value)} placeholder="z. B. 1.400 €"/></label><label>Kaltmiete SOLL jährlich<input value={data.rentTargetYear} onChange={e=>update("rentTargetYear",e.target.value)} placeholder="z. B. 16.800 €"/></label></div></>}
    {step===5&&<><p className="eyebrow">Schritt 5 von 7</p><h2>Zustand & Baujahr</h2><p className="tool-intro">Ordnen Sie den aktuellen Zustand in Schulnoten ein.</p><div className="condition-grid">{conditions.map(([item,description])=><button type="button" className={data.condition===item?"selected":""} onClick={()=>update("condition",item)} key={item}><strong>{item}</strong><small>{description}</small></button>)}</div><label>Baujahr *<input type="number" min="1800" max="2026" value={data.year} onChange={e=>update("year",e.target.value)} placeholder="z. B. 1965"/></label></>}
    {step===6&&<><p className="eyebrow">Schritt 6 von 7</p><h2>Ihre Kontaktdaten</h2><p className="tool-intro">Damit wir die Bewertung persönlich prüfen und mit Ihnen besprechen können.</p><div className="form-row"><label>Vorname *<input value={data.first} onChange={e=>update("first",e.target.value)} autoComplete="given-name"/></label><label>Nachname *<input value={data.last} onChange={e=>update("last",e.target.value)} autoComplete="family-name"/></label></div><div className="form-row"><label>E-Mail *<input type="email" value={data.email} onChange={e=>update("email",e.target.value)} autoComplete="email"/></label><label>Telefon *<input type="tel" value={data.phone} onChange={e=>update("phone",e.target.value)} autoComplete="tel"/></label></div><label>Ihre Adresse (optional)<input value={data.contactAddress} onChange={e=>update("contactAddress",e.target.value)} placeholder="Straße und Hausnummer"/></label><div className="form-row"><label>PLZ<input value={data.contactZip} onChange={e=>update("contactZip",e.target.value)} inputMode="numeric"/></label><label>Ort<input value={data.contactCity} onChange={e=>update("contactCity",e.target.value)}/></label></div><label className="tool-consent"><input type="checkbox" checked={data.consent==="yes"} onChange={e=>update("consent",e.target.checked?"yes":"")}/> Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung der Bewertungsanfrage gespeichert und verarbeitet werden. *</label></>}
    {step===7&&<><p className="eyebrow">Schritt 7 von 7</p><h2>Angaben prüfen</h2><div className="summary"><p><span>Immobilie</span><strong>{data.type}</strong></p><p><span>Adresse</span><strong>{data.street} {data.number}, {data.zip} Bergisch Gladbach-{data.district}</strong></p><p><span>Flächen</span><strong>{data.living&&`${data.living} m² Wohnfläche`}{data.living&&data.plot?" · ":""}{data.plot&&`${data.plot} m² Grundstück`}</strong></p><p><span>Zustand / Baujahr</span><strong>{data.condition} · {data.year}</strong></p></div><div className="valuation-notice"><strong>Persönliche Marktwerteinschätzung</strong><p>Es wird bewusst kein automatisch erfundener Marktwert ausgegeben. Der Standort prüft Ihre Angaben anhand des Grundstücksmarktberichts 2026, der konkreten Lage und der individuellen Objektmerkmale.</p></div>{sent&&<p className="sent-note">Die Anfrage wurde für Ihr E-Mail-Programm vorbereitet.</p>}</>}
    <div className="tool-actions">{step>1&&<button type="button" className="button outline" onClick={back}>Zurück</button>}{step<6&&<button type="button" className="button gold" disabled={!canContinue} onClick={next}>Weiter</button>}{step===6&&<button type="button" className="button gold" disabled={!canContinue} onClick={submit}>Bewertung anfordern</button>}{step===7&&!sent&&<button type="button" className="button gold" onClick={submit}>Bewertung anfordern</button>}</div>
  </div></div>;
}
