"use client";
import { useEffect, useMemo, useState } from "react";

type StreetRow={street:string;range:string;zip:string;district:string};

const propertyTypes=["Wohnung","Haus","Mehrfamilienhaus","Grundstück"];
const conditions=["1 – Sehr gut","2 – Gut","3 – Befriedigend","4 – Ausreichend","5 – Mangelhaft","6 – Ungenügend"];

export default function BewertungsForm(){
  const [step,setStep]=useState(1); const [sent,setSent]=useState(false); const [streetRows,setStreetRows]=useState<StreetRow[]>([]);
  const [data,setData]=useState<Record<string,string>>({type:"",street:"",number:"",zip:"",city:"Bergisch Gladbach",living:"",plot:"",rooms:"",units:"",rent:"",condition:"",year:"",first:"",last:"",email:"",phone:""});
  useEffect(()=>{fetch("/BGL/strassen-plz-bergisch-gladbach.csv").then(response=>response.text()).then(text=>{const rows=text.replace(/^\uFEFF/,"").trim().split(/\r?\n/).slice(1).map(line=>line.split(";").map(value=>value.replace(/^"|"$/g,"").replace(/""/g,'"'))).filter(parts=>parts.length>=4).map(parts=>({street:parts[0],range:parts[1],zip:parts[2],district:parts[3]}));setStreetRows(rows);}).catch(()=>setStreetRows([]));},[]);
  const streets=useMemo(()=>Array.from(new Set(streetRows.map(row=>row.street))).sort((a,b)=>a.localeCompare(b,"de")),[streetRows]);
  const matchingRows=useMemo(()=>streetRows.filter(row=>row.street===data.street),[streetRows,data.street]);
  const postcodeOptions=useMemo(()=>Array.from(new Set(matchingRows.map(row=>row.zip).filter(Boolean))).sort(),[matchingRows]);
  const districtOptions=useMemo(()=>Array.from(new Set(matchingRows.map(row=>row.district).filter(Boolean))).sort(),[matchingRows]);
  const update=(key:string,value:string)=>setData(prev=>({...prev,[key]:value}));
  const updateStreet=(value:string)=>{const matches=streetRows.filter(row=>row.street===value);const postcodes=Array.from(new Set(matches.map(row=>row.zip).filter(Boolean)));setData(prev=>({...prev,street:value,zip:postcodes.length===1?postcodes[0]:prev.street===value?prev.zip:""}));};
  const next=()=>setStep(value=>Math.min(7,value+1)); const back=()=>setStep(value=>Math.max(1,value-1));
  const submit=()=>{ const subject=`Immobilienbewertung ${data.street} ${data.number}, ${data.city}`; const body=[`Immobilientyp: ${data.type}`,`Adresse: ${data.street} ${data.number}, ${data.zip} ${data.city}`,`Wohnfläche: ${data.living} m²`,`Grundstück: ${data.plot} m²`,`Zimmer: ${data.rooms}`,`Wohneinheiten: ${data.units}`,`Kaltmiete: ${data.rent}`,`Zustand: ${data.condition}`,`Baujahr: ${data.year}`,`Kontakt: ${data.first} ${data.last}, ${data.email}, ${data.phone}`].join("\n"); setSent(true); window.location.href=`mailto:bergischgladbach@evernest.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; };
  const canContinue=step===1?!!data.type:step===2?!!data.street&&!!data.zip:step===3?!!data.living||!!data.plot:step===5?!!data.condition&&!!data.year:step===6?!!data.first&&!!data.last&&!!data.email&&!!data.phone:true;
  return <div className="valuation-tool">
    <div className="progress">{[1,2,3,4,5,6,7].map(n=><span className={n<=step?"active":""} key={n}>{n}</span>)}</div>
    <div className="tool-panel">
      {step===1&&<><p className="eyebrow">Schritt 1</p><h2>Was möchten Sie bewerten?</h2><p className="tool-intro">Wählen Sie die Art Ihrer Immobilie.</p><div className="type-grid">{propertyTypes.map(type=><button className={data.type===type?"selected":""} onClick={()=>update("type",type)} key={type}><span>{type==="Wohnung"?"▤":type==="Haus"?"⌂":type==="Mehrfamilienhaus"?"▥":"◇"}</span>{type}</button>)}</div></>}
      {step===2&&<><p className="eyebrow">Schritt 2</p><h2>Adresse der Immobilie</h2><p className="tool-intro">Wählen Sie eine Straße aus dem amtlichen Straßenverzeichnis. Bei eindeutiger Zuordnung wird die Postleitzahl automatisch ergänzt.</p><div className="form-row"><label>Straße *<input list="street-options" value={data.street} onChange={e=>updateStreet(e.target.value)} placeholder="Straßenname" autoComplete="street-address"/><datalist id="street-options">{streets.map(street=><option value={street} key={street}/>)}</datalist></label><label>Hausnummer<input value={data.number} onChange={e=>update("number",e.target.value)} placeholder="12"/></label></div><div className="form-row"><label>PLZ *<input list="postcode-options" value={data.zip} onChange={e=>update("zip",e.target.value)} inputMode="numeric" placeholder="PLZ"/><datalist id="postcode-options">{postcodeOptions.map(zip=><option value={zip} key={zip}/>)}</datalist></label><label>Ort<input value={data.city} onChange={e=>update("city",e.target.value)}/></label></div>{districtOptions.length>0&&<p className="privacy-note">Amtliche Zuordnung: {districtOptions.join(", ")}{postcodeOptions.length>1?" · Bitte PLZ anhand der Hausnummer wählen.":""}</p>}<p className="privacy-note">Quelle: Stadt Bergisch Gladbach, Straßenabfrage · 1.004 Straßen · abgerufen am 22.08.2026.</p></>}
      {step===3&&<><p className="eyebrow">Schritt 3</p><h2>Wie groß ist die Immobilie?</h2><p className="tool-intro">Geben Sie die vorhandenen Flächen an.</p><label>Wohnfläche in m²<input type="number" value={data.living} onChange={e=>update("living",e.target.value)} placeholder="z. B. 120"/></label><label>Grundstücksfläche in m²<input type="number" value={data.plot} onChange={e=>update("plot",e.target.value)} placeholder="z. B. 450"/></label></>}
      {step===4&&<><p className="eyebrow">Schritt 4</p><h2>Weitere Angaben</h2><p className="tool-intro">Diese Angaben helfen bei der persönlichen Einordnung.</p><div className="form-row"><label>Anzahl Zimmer<input type="number" value={data.rooms} onChange={e=>update("rooms",e.target.value)}/></label><label>Anzahl Wohneinheiten<input type="number" value={data.units} onChange={e=>update("units",e.target.value)}/></label></div><label>Aktuelle Nettokaltmiete monatlich<input value={data.rent} onChange={e=>update("rent",e.target.value)} placeholder="optional"/></label></>}
      {step===5&&<><p className="eyebrow">Schritt 5</p><h2>Zustand & Baujahr</h2><p className="tool-intro">Ordnen Sie den aktuellen Zustand ein.</p><div className="condition-grid">{conditions.map(item=><button className={data.condition===item?"selected":""} onClick={()=>update("condition",item)} key={item}>{item}</button>)}</div><label>Baujahr *<input type="number" value={data.year} onChange={e=>update("year",e.target.value)} placeholder="z. B. 1965"/></label></>}
      {step===6&&<><p className="eyebrow">Schritt 6</p><h2>Ihre Kontaktdaten</h2><p className="tool-intro">Für die Bearbeitung Ihrer persönlichen Bewertung.</p><div className="form-row"><label>Vorname *<input value={data.first} onChange={e=>update("first",e.target.value)}/></label><label>Nachname *<input value={data.last} onChange={e=>update("last",e.target.value)}/></label></div><label>E-Mail *<input type="email" value={data.email} onChange={e=>update("email",e.target.value)}/></label><label>Telefon *<input type="tel" value={data.phone} onChange={e=>update("phone",e.target.value)}/></label></>}
      {step===7&&<><p className="eyebrow">Schritt 7</p><h2>Angaben prüfen</h2><div className="summary"><p><span>Immobilie</span><strong>{data.type}</strong></p><p><span>Adresse</span><strong>{data.street} {data.number}, {data.zip} {data.city}</strong></p><p><span>Flächen</span><strong>{data.living&&`${data.living} m² Wohnfläche`}{data.living&&data.plot?" · ":""}{data.plot&&`${data.plot} m² Grundstück`}</strong></p><p><span>Zustand / Baujahr</span><strong>{data.condition} · {data.year}</strong></p></div><p className="privacy-note">Mit dem Absenden öffnen Sie Ihr E-Mail-Programm mit den erfassten Angaben. Es wird kein automatisch berechneter Marktwert ausgegeben; die Bewertung erfolgt nach Prüfung durch das Team.</p>{sent&&<p className="sent-note">Die Anfrage wurde für Ihr E-Mail-Programm vorbereitet.</p>}</>}
      <div className="tool-actions">{step>1&&<button className="button outline" onClick={back}>Zurück</button>}{step<7?<button className="button gold" disabled={!canContinue} onClick={next}>Weiter</button>:<button className="button gold" onClick={submit}>Bewertung anfordern</button>}</div>
    </div>
  </div>;
}
