import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { districtBySlug, districts } from "../../stadtteile";

export function generateStaticParams(){ return districts.map(({slug})=>({slug})); }

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params; const district=districtBySlug(slug);
  if(!district) return {};
  return {title:`Immobilienmakler ${district.name} | Bodenrichtwert & Verkauf`,description:`Immobilienverkauf und Bodenrichtwerte in Bergisch Gladbach-${district.name}: amtliche Einordnung, lokale Beratung und kostenlose Immobilienbewertung.`};
}

export default async function DistrictPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const district=districtBySlug(slug); if(!district) notFound();
  const position=districts.findIndex((item)=>item.slug===slug); const nearby=[districts[(position+24)%25],districts[(position+1)%25]];
  return <main className="district-page">
    <header className="site-header"><a className="brand" href="/BGL/"><span className="brand-mark">S<span>&</span>H</span><span><strong>Stark & Hoffmann</strong><small>Immobilien · Bergisch Gladbach</small></span></a><nav aria-label="Seitennavigation"><a href="/BGL/#profil">Profil</a><a href="/BGL/#fahrplan">Verkaufsfahrplan</a><a href="/BGL/#immobilien">Immobilien</a><a href="/BGL/#staedte">Stadtteile</a></nav><a className="header-cta" href="#kontakt">Kostenlose Bewertung</a></header>
    <section className="district-hero"><div><p className="eyebrow light">Immobilienmakler Bergisch Gladbach</p><h1>{district.name}</h1><p>Immobilien verkaufen und bewerten – mit persönlicher Beratung durch den Standort Bergisch Gladbach.</p><a className="button gold" href="#kontakt">Immobilie bewerten lassen</a></div></section>
    <section className="district-intro section"><div><p className="eyebrow">Stadtteilprofil</p><h2>Immobilien in {district.name}</h2><p className="lead">{district.name} ist der amtliche Stadtteil {district.code} der Stadt Bergisch Gladbach und gehört zum {district.area.toLowerCase()}.</p><p>Zum 31. Dezember 2025 lebten hier <strong>{district.inhabitants} Einwohner</strong>. Für eine Immobilienbewertung werden neben der konkreten Lage auch Grundstück, Baujahr, Zustand, Nutzung und Energieeffizienz betrachtet.</p><a className="source-link" href="https://www.bergischgladbach.de/entwicklung.aspx" target="_blank" rel="noreferrer">Quelle: Stadt Bergisch Gladbach, Statistikdienststelle ↗</a></div><aside><span>Stadtteilnummer</span><strong>{district.code}</strong><span>Einwohner 2025</span><strong>{district.inhabitants}</strong><small>Stand: 31.12.2025</small></aside></section>
    <section className="brw section" id="bodenrichtwert"><div className="section-head"><div><p className="eyebrow light">Bodenrichtwert {district.name}</p><h2>Amtliche Werte zum 01.01.2026.</h2></div><p>Der Gutachterausschuss hat für Bergisch Gladbach 286 Bodenrichtwertzonen in Wohngebieten ermittelt. Maßgeblich bleibt deshalb die Zone der konkreten Adresse.</p></div>
      {district.brw ? <div className="district-range"><span>Bodenwertspanne für Ein- und Zweifamilienhäuser</span><strong>{district.brw} €/m²</strong><p>Im Grundstücksmarktbericht 2026 ausgewiesen für: {district.brwGroup}.</p></div> : <div className="district-range no-value"><span>Ein- und Zweifamilienhäuser in {district.name}</span><strong>Keine eigene Stadtteilspanne veröffentlicht</strong><p>Der Grundstücksmarktbericht 2026 nennt für {district.name} keine separate Bodenwertspanne. Der amtliche Wert ist daher ausschließlich adressgenau über BORIS-NRW abrufbar.</p></div>}
      <h3 className="table-title">Gebietstypische Bodenrichtwerte Bergisch Gladbach</h3><div className="brw-table-wrap"><table className="brw-table"><thead><tr><th>Unbebaute Grundstücke</th><th>Gute Lage</th><th>Mittlere Lage</th><th>Einfache Lage</th></tr></thead><tbody><tr><td>Freistehende Ein- und Zweifamilienhäuser</td><td>970 €/m²</td><td>660 €/m²</td><td>510 €/m²</td></tr><tr><td>Doppelhaushälften und Reihenendhäuser</td><td>790 €/m²</td><td>570 €/m²</td><td>510 €/m²</td></tr><tr><td>Reihenmittelhäuser</td><td>850 €/m²</td><td>610 €/m²</td><td>490 €/m²</td></tr></tbody></table></div>
      <div className="source-note"><p><strong>Stichtag 01.01.2026.</strong> Die Werte gelten für baureife, erschließungs- und kanalanschlussbeitragsfreie Grundstücke. Lage, Grundstücksgröße und -tiefe, Bodenbeschaffenheit, bauliche Nutzung und Erschließungszustand können zu erheblichen Abweichungen führen.</p><div><a className="button gold" href="https://www.boris.nrw.de/" target="_blank" rel="noreferrer">Adresse in BORIS-NRW prüfen ↗</a><a className="source-link light" href="https://www.gars.nrw/stadt-gl/produkte-gl/grundstuecksmarktbericht-gl" target="_blank" rel="noreferrer">Quelle: Grundstücksmarktbericht 2026, S. 5 und 27–32 ↗</a></div></div>
    </section>
    <section className="valuation section"><p className="eyebrow">Was Ihre Immobilie wirklich wert ist</p><h2>Der Bodenrichtwert ist nur ein Teil der Bewertung.</h2><div className="valuation-grid"><p>Abweichungen bei Art und Maß der baulichen Nutzung, Bodenbeschaffenheit, Erschließungszustand und Grundstücksgestaltung können zu einem vom Bodenrichtwert abweichenden Grundstückswert führen.</p><ul><li>Konkrete Bodenrichtwertzone</li><li>Art und Maß der baulichen Nutzung</li><li>Bodenbeschaffenheit und Erschließung</li><li>Zuschnitt und Gestaltung des Grundstücks</li></ul></div><a className="source-link" href="https://open.nrw/dataset/ce127d47-27d1-4f49-a4dc-65cc1dac339e" target="_blank" rel="noreferrer">Quelle: Open.NRW – Bodenrichtwerte NRW ↗</a></section>
    <section className="nearby section"><p className="eyebrow">Weitere Stadtteile</p><div>{nearby.map(item=><a href={`/BGL/stadtteile/${item.slug}/`} key={item.slug}><span>Immobilienmakler</span><strong>{item.name}</strong><b>→</b></a>)}</div></section>
    <section className="district-contact section" id="kontakt"><div><p className="eyebrow light">Kostenlose Erstberatung</p><h2>Immobilienbewertung in {district.name}</h2><p>Unverbindliche Anfrage an unser Team in Bergisch Gladbach.</p></div><div><a className="button gold" href={`mailto:bergischgladbach@evernest.com?subject=Immobilienbewertung%20${district.name}`}>Bewertung anfragen</a><a href="tel:+4922049147881">+49 2204 914 7881</a></div></section>
    <footer><div className="footer-brand"><span className="brand-mark">S<span>&</span>H</span><div><strong>Stark & Hoffmann Immobilien</strong><small>Evernest Lizenzpartner Bergisch Gladbach</small></div></div><div><h4>Kontakt</h4><p>Schloßstraße 41<br/>51429 Bergisch Gladbach</p><a href="tel:+4922049147881">+49 2204 914 7881</a></div><div><h4>Quellen</h4><a href="https://www.boris.nrw.de/">BORIS-NRW</a><a href="https://www.gars.nrw/stadt-gl/produkte-gl/bodenrichtwerte-gl">Gutachterausschuss</a></div><div><h4>Hinweis</h4><p>Bodenrichtwerte sind Orientierungswerte und keine Verkehrswerte. Alle Angaben unverbindlich.</p></div></footer>
  </main>;
}
